services:
  app:
    image: myfav_quotes-api:latest
    build:
      context: .
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - '8080:8080'
    command: ["--hostname", "0.0.0.0", "--port", "8080"]
  db:
    image: postgres:16.3-alpine3.20
    volumes:
      - db_data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    ports:
      - 5432:5432
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8888:80"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      
volumes:
  db_data:
  pgadmin-data:
